name: SpotBugs Code Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spotbugs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradle wrapper executable
        run: cd app && chmod +x ./gradlew

      - name: Run SpotBugs Analysis
        run: ./gradlew compileJava spotbugsMain --continue

      - name: Upload SpotBugs SARIF Report
        uses: github/codeql-action/upload-sarif@v4

        if: always()
        with:
          sarif_file: build/reports/spotbugs/main.sarif
